CREATE TABLE "company"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT company_pkey
        PRIMARY KEY,
    name            VARCHAR(500) NOT NULL,
    ogrn            VARCHAR(256) NOT NULL,
    description     VARCHAR(1000) NOT NULL,
    director_id     BIGINT
)